### ISSUE TITLE
Problem with cho45 web interface

### ISSUE THREAD

**Issue by Ernie49** [cho45/NanoVNA-Web-Client#8]
Whenever I start https://cho45.stfuawsc.com/NanoVNA/ from within Chrome browser running under Windows10 x64) I get a short message at the bottom flashing up with message "Security error: must be handling a user gesture to show a permission request".
When trying to connect another message appears "Type error cannot read type "1" of null".
I use hugens latest firmware dated 20191009. No problem with NanoVNA saver.
Any ideas?
Thanks

**Comment by cho45** [comment]
1. What do you use interface type? WebUSB or WebSerial?
![スクリーンショット 2019-10-18 8 42 46](https://user-images.githubusercontent.com/3092/67055502-50caf980-f183-11e9-8ef6-b15fcea10b94.png)

2. With WebUSB: You must replace driver.
See https://github.com/cho45/NanoVNA-Web-Client#windows

**Comment by hugen79** [comment]
May be the compilation problem caused by the flash usage limit, I have re-compiled after removing the sin/cos table in my firmware, now it can connect to the web interface normally.

**Comment by Ernie49** [comment]
Hugen, thanks for adapting the firmware. Now works ok.

 

Greetings from Germany

Ernst, DK1VI

 

Von: hugen79 [mailto:notifications@github.com] 
Gesendet: Freitag, 18. Oktober 2019 07:41
An: cho45/NanoVNA-Web-Client <NanoVNA-Web-Client@noreply.github.com>
Cc: Ernie49 <dk1vi@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [cho45/NanoVNA-Web-Client] Problem with cho45 web interface (#8)

 

May be the compilation problem caused by the flash usage limit, I have re-compiled after removing the sin/cos table in my firmware, now it can connect to the web interface normally.

**Comment by Ernie49** [comment]
Sorry form my late reply but I was very busy recently.

 

Hugen has modified his firmware and now it works.

 

Thank you.

 

Greetings from Germany

Ernst, DK1VI

 

Von: Satoh, Hiroh [mailto:notifications@github.com] 
Gesendet: Freitag, 18. Oktober 2019 01:44
An: cho45/NanoVNA-Web-Client <NanoVNA-Web-Client@noreply.github.com>
Cc: Ernie49 <dk1vi@gmx.de>; Author <author@noreply.github.com>
Betreff: Re: [cho45/NanoVNA-Web-Client] Problem with cho45 web interface (#8)

 

1.      What do you use interface type? WebUSB or WebSerial?
 <https://user-images.githubusercontent.com/3092/67055502-50caf980-f183-11e9-8ef6-b15fcea10b94.png> 

2.      With WebUSB: You must replace driver.
See https://github.com/cho45/NanoVNA-Web-Client#windows

**Comment by hugen79** [comment]
Hello, cho45, I re-examined the problem and found that the problem was caused by the uncommitted version when compiling the firmware, causing the “version” command to return an empty string.

**Comment by cho45** [comment]
I found an issue for parsing build time and fixed on https://github.com/cho45/NanoVNA-Web-Client/commit/e20d9ae15a7ff1461535ad65e44513edeb244f20 .
